FROM ultralytics/ultralytics:latest
COPY requirements.txt requirements.txt
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
COPY setup.py setup.py
COPY league league/
RUN pip install -e .
CMD python -m league.motion_tracking.train
